In [6]:
columns_to_use = ['LEAVE_TIME', 'STOP_TIME']

In [7]:
import pandas as pd
file3 = "/Users/kathypresto/Desktop/trimet/Big_Data/untitled folder 3/trimet_stop_event_2023_2024.csv"
df_2023 = pd.read_csv(file3, usecols=columns_to_use)

In [8]:
df_2023['DELAY_MINUTES'] = (df_2023['LEAVE_TIME'] - df_2023['STOP_TIME']) / 60
df_2023['ON_TIME'] = df_2023['DELAY_MINUTES'].between(-1, 5).astype(int)

In [9]:
df_2023['LEAVE_HOUR'] = df_2023['LEAVE_TIME'] // 3600  # if it's in seconds past midnight

In [14]:
df_2023.head()

   LEAVE_TIME  STOP_TIME  DELAY_MINUTES  ON_TIME  LEAVE_HOUR
0       43689      43740      -0.850000        1          12
1       74647      74220       7.116667        0          20
2       55903      56081      -2.966667        0          15
3       55992      56160      -2.800000        0          15
4       57143      57060       1.383333        1          15

In [16]:
def map_time_bin(seconds):
    if seconds <= 21600:
        return 'Early'
    elif seconds <= 54000:
        return 'Day'
    elif seconds <= 79200:
        return 'Evening'
    else:
        return 'Late Night'

df_2023['TIME_BIN'] = df_2023['LEAVE_TIME'].apply(map_time_bin)

In [18]:
df_2023.head()

   LEAVE_TIME  STOP_TIME  DELAY_MINUTES  ON_TIME  LEAVE_HOUR TIME_BIN
0       43689      43740      -0.850000        1          12      Day
1       74647      74220       7.116667        0          20  Evening
2       55903      56081      -2.966667        0          15  Evening
3       55992      56160      -2.800000        0          15  Evening
4       57143      57060       1.383333        1          15  Evening

In [20]:
from scipy.stats import chi2_contingency
import pandas as pd

# Create the contingency table
contingency_table = pd.crosstab(df_2023['TIME_BIN'], df_2023['ON_TIME'])

# Run chi-square test
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Display results
print("Contingency Table:")
print(contingency_table)
print("\nChi-Square Test Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("P-Value:", p)

Contingency Table:
ON_TIME            0         1
TIME_BIN
Day         10804614  37178675
Early         588338   1949033
Evening      9457628  25280696
Late Night   1559818   5002526

Chi-Square Test Statistic: 245908.15433372662
Degrees of Freedom: 3
P-Value: 0.0